version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on: 
      - couchdb 
    environment:
      COUCHBASE_HOST: couchdb
      COUCHDB_USER: Administrator
      COUCHDB_PASSWORD: password
      COUCHBASE_BUCKET: restful
  
  couchdb:
    build:
      context: ./couchbase
      dockerfile: Dockerfile
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: Administrator
      COUCHBASE_ADMINISTRATOR_PASSWORD: password
      COUCHBASE_BUCKET: restful  
      COUCHBASE_BUCKET_PASSWORD: